module.exports = {
   build: build
}
const pfs = require('fs').promises;
const fs = require('fs');
const path = require('path');


async function walk(dir, fileList = []) {
   const files = await pfs.readdir(dir);
   for (const file of files) {
      const stat = await pfs.stat(path.join(dir, file));
      if (stat.isDirectory()) {
         fileList = await walk(path.join(dir, file), fileList);
      } else {
         const segments = dir.split('\\');
         const parentFolder = segments[segments.length - 1];
         if (file === parentFolder + '.html') {
            var filePath = path.join(dir, file);
            fileList.push(filePath);
         }
      }
   }
   return fileList;
}

function build(dir) {

   console.log(`build layouts: ${dir}`);

   var layouts = [];
   walk(dir).then((files) => {
      for (var i = 0; i < files.length; i++) {
         var filePath = files[i];
         var segments = filePath.split('\\');
         var name = segments.pop();
         name = name.replace('.html', '')
         createTemplateJs(filePath);
         layouts.push(`'${name}': require('./${name}/${name}.html.js')`);
      }
      generateComponents(dir, layouts);
   });
}

function generateComponents(dir, layouts) {

   var js = `// auto generated by build/layouts.js

module.exports = {
   get: get
};

const layouts = {
   ${layouts.join(',\n\t')}
};

function get(type) {
   if (layouts[type] == null) {
      console.log('layout not found for ', type);
   }

   return layouts[type].get();
}`;

   js = js.replace(/\uFEFF/g, '');
   fs.writeFileSync(`${dir}\\factory.js`, js, 'utf8', function (err) {});
}

function createTemplateJs(filePath) {

   var html = fs.readFileSync(filePath, 'utf8');
   var js = `// auto generated by build/layouts.js

   module.exports = {
      get
   };

   function get() {
      return \`${html}\`;
   }`;

   js = js.replace(/\uFEFF/g, '');
   fs.writeFileSync(filePath + '.js', js, 'utf8', function (err) {
      console.log(err)
   });
}